steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: Build and Deploy to Dev Server
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -x && \
        gcloud compute ssh --zone=${_ENV_ZONE} ${_ENV_INST_USER}@${_ENV_INST_NAME} --command='export APP_PATH=${_ENV_APP_PATH}; cd ${_ENV_PULL_PATH}; git pull origin ${_ENV_BRANCH}; ./deploy.sh'
substitutions:
  _ENV_ZONE: "_env_zone:latest" # Secret Manager reference
  _ENV_INST_USER: "_env_inst_user:latest" # Secret Manager reference
  _ENV_INST_NAME: "_env_inst_name:latest" # Secret Manager reference
  _ENV_BRANCH: "_env_branch:latest" # Secret Manager reference
  _ENV_APP_PATH: "_env_app_path:latest" # Secret Manager reference
  _ENV_PULL_PATH: "_env_pull_path:latest" # Secret Manager reference
options:
  logging: CLOUD_LOGGING_ONLY
